
version: '3.8'

services:
    mysql-db:
        image: mysql:8.0
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: autos-10a
            MYSQL_USER: autos
            MYSQL_PASSWORD: passwordautos
    web:
        build:
            context: ./gpds-autos
            dockerfile: Dockerfile
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/autos-10a
            SPRING_DATASOURCE_USERNAME: autos
            SPRING_DATASOURCE_PASSWORD: passwordautos
            SPRING_DATASOURCE_HIBERNATE_DDL_AUTO: update
        ports:
            - "8000:8080" # Exponer el puerto 80 de nginx en el puerto 8080 de tu host
        depends_on:
            - mysql-db
